apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnd-ai-master
  namespace: dnd-ai-master
  labels:
    app: dnd-ai-master
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dnd-ai-master
  template:
    metadata:
      labels:
        app: dnd-ai-master
    spec:
      containers:
      - name: dnd-ai-master
        image: dnd-ai-master:latest
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 3001
          name: socket
        env:
        - name: NEXT_PUBLIC_SOCKET_URL
          valueFrom:
            configMapKeyRef:
              name: dnd-ai-config
              key: NEXT_PUBLIC_SOCKET_URL
        - name: NEXTAUTH_URL
          valueFrom:
            configMapKeyRef:
              name: dnd-ai-config
              key: NEXTAUTH_URL
        - name: COHERE_API_KEY
          valueFrom:
            secretKeyRef:
              name: dnd-ai-secrets
              key: cohere-api-key
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: dnd-ai-secrets
              key: nextauth-secret
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: DATABASE_URL
          value: "postgresql://dnd_user:$(POSTGRES_PASSWORD)@postgres-service:5432/dnd_ai"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dnd-ai-secrets
              key: postgres-password
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: dnd-ai-config
